<?php

namespace AppBundle\Repository;

/**
 * ChatonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatonRepository extends \Doctrine\ORM\EntityRepository
{
}
