<?php

namespace AppBundle\Repository;

/**
 * PropriétaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropriétaireRepository extends \Doctrine\ORM\EntityRepository
{
}
